namespace ArchersNetwork.Backend.Features.Video.Dto;

/// <summary>
/// DTO for returning video data in responses.
/// Includes the ID generated by the database.
/// </summary>
public record VideoResponseDto(
    int Id,
    string Title,
    DateTime Date,
    string Description,
    string Link,
    string Channel,
    string Series
);